# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sRNABench', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='short_name',
        ),
        migrations.AddField(
            model_name='species',
            name='db',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='db_ver',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='hasTargetSequencesAndGO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='scientific',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='shortName',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='sp_class',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='specie',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='taxID',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
