# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('pipeline_key', models.CharField(max_length=100)),
                ('job_status', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=0)),
                ('finish_time', models.DateTimeField(default=0)),
                ('all_files', models.CharField(max_length=1000)),
                ('modules_files', models.CharField(max_length=1000)),
                ('pipeline_type', models.CharField(max_length=100)),
                ('heatmaps', models.CharField(max_length=1000)),
                ('xls_files', models.CharField(max_length=1000)),
                ('zip_file', models.CharField(max_length=1000)),
                ('stats_file', models.CharField(max_length=1000)),
                ('blast_file', models.CharField(max_length=1000)),
                ('species_file', models.CharField(max_length=1000)),
                ('tax_file', models.CharField(max_length=1000)),
                ('tax_svg', models.CharField(max_length=1000)),
                ('species_svg', models.CharField(max_length=1000)),
                ('bed_files', models.CharField(max_length=1000)),
                ('ts_file', models.CharField(max_length=1000)),
                ('pita_file', models.CharField(max_length=1000)),
                ('miranda_file', models.CharField(max_length=1000)),
                ('consensus_file', models.CharField(max_length=1000)),
                ('info_file', models.CharField(max_length=1000)),
                ('micro_file', models.CharField(max_length=1000)),
                ('outdir', models.CharField(max_length=1000)),
                ('parameters', models.CharField(max_length=1000)),
                ('command_line', models.CharField(max_length=1000)),
                ('java_commad_line', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_progress', models.CharField(max_length=1000)),
                ('JobStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.JobStatus')),
            ],
        ),
    ]
