# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='bed_files',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='blast_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='consensus_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='heatmaps',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='info_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='java_commad_line',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='micro_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='miranda_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='parameters',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='pita_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='species_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='species_svg',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='stats_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='tax_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='tax_svg',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='ts_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='xls_files',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='zip_file',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='JobStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='progress.JobStatus'),
        ),
    ]
